[project]
name = 'yieldforge'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.yield-insight]
path = 'contracts/yield-insight.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
